# -----------------------------------Is there a KS Boom ?-------------------------------------
### Exploring the impact of the KS bloom Phenomenon on youngster social networks in Ivory coast

# Genesis

On March 10th 2021, a whatsapp user called Kevin Bloom (uKB) creates a group called "GIGA_PUB "ALBUM KS" quoting on March 13th:

*The object of the group*

"Ce groupe est là à 100% pour le salut des âmes, mais comme les gens refusent d'entendre le pur évengile, l'évengile viendra vers eux de façon subtile, caché dans la musique de notre frère **KS Bloom** , c'est comme ça que nous pourrons les avoirs ! On va envahir la toile, on va faire un tapage énorme à la sortie de l'album pendant au moin une semaine ! Pour que le plus de personne l'écoute et reçoive l'évengile! C'est pour ça qu'on est tous là [smiley feu]

Which may be translated in English:

"This group is 100% about saving souls. But since people tend to not receive the raw gospel, this gospel will reach them subtly hidden inside the music of our brother **KS Bloom**. We'll get them into it this way! We'll overflow the web, making a lot of noise for the release of the album for one good week! This aims at letting the most people possible be exposed to the gospel through listening the music. This is the point here ! [smiley fire]


*The Tactics*

uKB later reveals that most of the work would be done on Facebook. It must target "the most influent groups" [among the youngsters], with the desire to "impact souls as much as possible". Four groups are targeted:

1. "ICI C'EST NOTRE CHAMP" URL: https://www.facebook.com/groups/366508221376496/
2. "Les IMMATURES [SMILEY] (RELAIS)" URL: https://www.facebook.com/groups/258444072185517/
3. "Les IMMATURES [SMILEY] (Officiel)" URL: https://www.facebook.com/groups/198765105368472/
4. "Buzz du jour[SMILEY][SMILEY][SMILEY] " URL: https://www.facebook.com/groups/134176048562334
5. ":: RAP IVOIRE :: - Le Groupe" URL: https://www.facebook.com/groups/164984320303259


*The Targets*

Their URLs date back to the posts then: March 13th. Some days later, all 5 groups were on, according to the personal observation of a witness. Some of them require to be admitted though. But as of today (Nov 8th, 2021) only #4 and #5 do exist or have the same URL as before. It is not easy to spot whether #1 #2 and #3 are still alive, having been "transferred" to another host URL. 

Based on the observation of a witness some days after March 13th,
#1 #2 and #3 are of the same kind, self-claiming a unique entertainment purpose. To a witness observation it gathered YOLO-minded young people who did posted dark, obscene or mocking content about other people, themselves and society. The main themes then observed are **humor**, **sex**, **gossip**, which we try to show through the E.D.A.
#4 slightly steps aside the latter
#5 promotes rap music made in Ivory Coast. It shares similar contents with the 4 others, but with a smaller quantity.

*The action*

**A first class of observations relates to the highlights of the life of the group itself.**

On March 13th a first recall is released by uKB. It reminds all that the purpose of the group is not to chat & chill, but to promote the then incoming album "Allumez La Lumière". He then insists on the freedom to leave the game if one doesn't share the said purpose.  At this moment the discussion, when made possible by the group admins, tend to mainly turn around chatting between members about other subjects than promoting the album.

On March 19th, a post probes on the pre-purchase of the album itself among the members.

On March 23th, the user Mr Beckaine (uBK) gives a special annoucement about the release of the album and its availability on various streaming platforms.

On March 24th, uKB launched the challenge "La danse de la victoire" 

On March 27


**A second class of observations relates to the actual implementation of the tactics.**

On March 14th and 15th, group members are thanked by uKB for having posted on the targeted groups.

On March 15th, 
The user Mr Beckaine (uBK) asks all whether they are successful in flooding their social media with the content privately shared in the group, and thanks all about their various commitments. 
uKB requires the users to substitute a promotional picture for their profile picture to boost visibility on whatsapp.

On March 19th,
uKB reminds all to suscribe to the targeted groups. He then requires all to post their feelings and comments about the album on the targeted groups. A member is specially thanked for a facebook post which gets a lot of hits on FB.

On March 24th,
A member (which is known to be a member of the staff) posts to report that posts related to KS Bloom are blocked. He suggests to use one's FB profiles as ad supports.
uKB reminds all to share the promotion posts through social media walls and status

On March 26th, 
uKB thanks all for their commitment, claiming a yet visible impact (on the social media). He shares some tangible elements about this impact.

# Project definition/frame

**Business opportunities**

B1. Digital influence measurement both qualitative and quantitative made available to an influencer

B2. Introduction of an alternative qualification/quantification of a public digital influence: based on the assessment of the influencer self-designed (not openly) goals.

B3. Availability of a dictionnary of terms specific to the sub-culture crossing *nouchi, rap ivoire, ivorian humor*. Ivorian urban/artistic subculture currently has a significant impact among the french-speaking african youth and diaspora (potentially several hundreds milions of people)

B4. Automatic classification of jargon-filled comments


**Objectives**

O1. Clean the raw comments extracted from targeted facebook groups

O2. Achieve an EDA of the text comments  

O3. Perform a dynamic topic analysis of the comments and possibly confront with the evolution of the group hashtags in time (if those statistics are available to the group admins, and if they grant access to it).

O4. Make it possible to automatically classify the members comments (espicially those not self-hashtagged), based on comments topics generated.

**Assumptions**

A1. There is a high interconnection within the mediatic world which displays the facts and highlights of this subculture: important web-hosted or TV shows litterally relay down to everyday buzzes or gossips booming the mediatic sphere.

A2. There is a common slang-like jargon spanning the whole subculture.

A3. The ivorian urban/artistic subculture has the strongest impact in the african french-speaking youth, originating mainly from urban music and humoristic production.

**Update of the tactics**

The targeted groups are enlarged at least for the achievement of objectives O3 and O4. This is due to (1) a relative scarcity of text comments among the posts observed on the initial targets (initiated by the influencer staff), (2) the assumptions A1 and A2.

**Deliverables**

D1. A notebook of the EDA of text comments

D2. A dictionnary of a subculture jargon

D3. Sets of comments topics 

D4. A notebook of pipeline of comments processing

**Requirements on the deliverables**

TO BE DEFINED

----------------------------------------------------------------------------------------







****************************************************************************************

# Implementation of the project

In [2]:
import pandas as pd
import numpy as np
import json
import timeit
import matplotlib.pyplot as plt

import nltk
from nltk.probability import FreqDist
import spacy
from langdetect import detect
from sklearn.feature_extraction.text import CountVectorizer;
from sklearn.feature_extraction.text import TfidfTransformer;
from sklearn.decomposition import NMF;
from sklearn.preprocessing import normalize;

import gensim as gsm
from gensim.models import Word2Vec
from gensim.models import FastText
from gensim.models import nmf
from gensim.models.coherencemodel import CoherenceModel
from gensim import corpora

import pickle

## Loading the data files

In [3]:
posts = pd.read_csv('ksbloomfbfull_posts.csv')

In [5]:
posts.describe()

,post_id,video_id,likes,comments,shares,user_id,factcheck,shared_post_id,shared_user_id
count,3.800000e+01,2.100000e+01,38.000000,38.000000,38.000000,3.800000e+01,0.0,5.000000e+00,5.000000e+00
mean,4.870870e+14,1.050534e+15,5594.342105,341.789474,37.789474,1.121059e+14,NaN,1.373592e+15,9.485816e+14
std,1.122508e+13,1.238291e+15,5888.293647,545.833365,97.724975,0.000000e+00,NaN,1.250269e+15,1.113642e+15
min,4.618022e+14,2.304106e+14,910.000000,23.000000,0.000000,1.121059e+14,NaN,2.702413e+14,1.000444e+14
25%,4.806149e+14,4.199615e+14,2022.000000,92.250000,0.000000,1.121059e+14,NaN,2.727363e+14,1.000445e+14
50%,4.900849e+14,4.733344e+14,4462.500000,157.000000,0.000000,1.121059e+14,NaN,9.005395e+14,2.076899e+14
75%,4.961363e+14,1.114300e+15,6758.500000,261.750000,0.000000,1.121059e+14,NaN,2.623376e+15,2.167565e+15
max,5.021554e+14,5.247102e+15,34616.000000,3014.000000,379.000000,1.121059e+14,NaN,2.801068e+15,2.167565e+15

In [21]:
posts.head()

,post_id,text,post_text,shared_text,time,image,video,video_thumbnail,video_id,likes,...,user_id,username,is_live,factcheck,shared_post_id,shared_time,shared_user_id,shared_username,shared_post_url,images
0,502155397837809,- UN DISCIPLE se reconnaît par son amour pour ...,- UN DISCIPLE se reconnaît par son amour pour ...,NaN,2021-03-18 20:06:48,https://scontent-cdg2-1.xx.fbcdn.net/v/t1.0-9/...,NaN,NaN,NaN,6814,...,112105906842762,Ks Bloom,False,NaN,NaN,NaN,NaN,NaN,NaN,['https://scontent-cdg2-1.xx.fbcdn.net/v/t1.0-...
1,501456827907666,"Jour j -6, RDV Ce 23 MARS pour l’album ""Allume...","Jour j -6, RDV Ce 23 MARS pour l’album ""Allume...",NaN,2021-03-17 20:29:23,NaN,https://video-cdt1-1.xx.fbcdn.net/v/t42.1790-2...,https://scontent-cdt1-1.xx.fbcdn.net/v/t15.525...,2.720774e+14,910,...,112105906842762,Ks Bloom,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,500770231309659,RDV CE MARDI 23 MARS LES DISCIPLES! Dans exact...,RDV CE MARDI 23 MARS LES DISCIPLES! Dans exact...,NaN,2021-03-16 20:13:33,NaN,https://video-cdg2-1.xx.fbcdn.net/v/t42.1790-2...,https://scontent-cdg2-1.xx.fbcdn.net/v/t15.525...,5.247102e+15,3251,...,112105906842762,Ks Bloom,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
3,500118784708137,"Jour j -8 , RDV Ce 23 MARS pour l’album ""Allum...","Jour j -8 , RDV Ce 23 MARS pour l’album ""Allum...",NaN,2021-03-15 20:34:19,NaN,https://video-cdt1-1.xx.fbcdn.net/v/t42.9040-2...,https://scontent-cdt1-1.xx.fbcdn.net/v/t15.525...,1.835932e+15,1057,...,112105906842762,Ks Bloom,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
4,499471664772849,LES DISCIPLES Jour J-9 !\n\nNon seulement L’al...,LES DISCIPLES Jour J-9 !\n\nNon seulement L’al...,NaN,2021-03-14 20:47:12,NaN,https://video-cdt1-1.xx.fbcdn.net/v/t42.9040-2...,https://scontent-cdg2-1.xx.fbcdn.net/v/t15.525...,5.722013e+14,2064,...,112105906842762,Ks Bloom,False,NaN,NaN,NaN,NaN,NaN,NaN,[]

In [8]:
posts.columns

Index(['post_id', 'text', 'post_text', 'shared_text', 'time', 'image', 'video',
       'video_thumbnail', 'video_id', 'likes', 'comments', 'shares',
       'post_url', 'link', 'user_id', 'username', 'is_live', 'factcheck',
       'shared_post_id', 'shared_time', 'shared_user_id', 'shared_username',
       'shared_post_url', 'images'],
      dtype='object')

In [22]:
1 - posts.isna().mean()

post_id            1.000000
text               0.921053
post_text          0.921053
shared_text        0.157895
time               1.000000
image              0.421053
video              0.552632
video_thumbnail    0.552632
video_id           0.552632
likes              1.000000
comments           1.000000
shares             1.000000
post_url           1.000000
link               0.578947
user_id            1.000000
username           1.000000
is_live            1.000000
factcheck          0.000000
shared_post_id     0.131579
shared_time        0.131579
shared_user_id     0.131579
shared_username    0.131579
shared_post_url    0.131579
images             1.000000
dtype: float64

In [14]:
buzz = pd.read_csv('buzzdujour_posts.csv')

In [20]:
buzz.head()

,post_id,text,post_text,shared_text,time,image,video,video_thumbnail,video_id,likes,...,user_id,username,is_live,factcheck,shared_post_id,shared_time,shared_user_id,shared_username,shared_post_url,images
0,844414989490063,Je faisais calmement l'amour à ma femme et Boo...,Je faisais calmement l'amour à ma femme et Boo...,NaN,2021-03-16 23:57:32,NaN,NaN,NaN,NaN,225,...,100055130234525,Roy Delaure,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
1,845931766005052,Ma chérie combien de mec te drague par jour?\n...,Ma chérie combien de mec te drague par jour?\n...,NaN,2021-03-19 17:07:32,NaN,NaN,NaN,NaN,4,...,100057202942245,Abidjan Buzz Aziz,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,845480162716879,NaN,NaN,NaN,2021-03-18 20:32:01,NaN,NaN,NaN,NaN,100,...,100023395822221,Kodesh Elvis Badi,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
3,844653756132853,Souvent tu l'a mougou et tellement ça dure tu ...,Souvent tu l'a mougou et tellement ça dure tu ...,NaN,2021-03-17 11:24:24,NaN,NaN,NaN,NaN,221,...,100050756594535,Ricky Lambert,False,NaN,NaN,NaN,NaN,NaN,NaN,[]
4,845000542764841,Petit malien là à quel gamme ?🤷🏽‍♂️🤦🏽,Petit malien là à quel gamme ?🤷🏽‍♂️🤦🏽,NaN,2021-03-18 00:38:47,NaN,NaN,NaN,NaN,759,...,100009527940646,Kone Bamoussa,False,NaN,NaN,NaN,NaN,NaN,NaN,[]

In [16]:
buzz.describe()

,post_id,video_id,likes,comments,shares,user_id,factcheck,shared_post_id,shared_user_id
count,2.000000e+02,2.400000e+01,200.000000,200.000000,200.000000,2.000000e+02,0.0,6.200000e+01,6.200000e+01
mean,8.454250e+14,9.261702e+14,39.275000,11.825000,1.025000,1.000334e+14,NaN,8.835464e+14,3.123032e+14
std,7.627248e+11,9.570090e+14,100.862758,24.576092,3.208715,1.940522e+10,NaN,1.235137e+15,5.306467e+14
min,8.403129e+14,1.397599e+14,0.000000,0.000000,0.000000,1.000022e+14,NaN,1.025803e+14,2.803816e+11
25%,8.453342e+14,2.760495e+14,0.000000,0.000000,0.000000,1.000124e+14,NaN,1.543820e+14,1.015337e+14
50%,8.457507e+14,7.372164e+14,4.000000,1.000000,0.000000,1.000332e+14,NaN,2.549116e+14,1.048067e+14
75%,8.458539e+14,8.818596e+14,33.250000,9.000000,0.000000,1.000526e+14,NaN,8.001598e+14,1.176023e+14
max,8.459627e+14,4.007033e+15,759.000000,133.000000,25.000000,1.000639e+14,NaN,4.283539e+15,2.350968e+15

In [19]:
1 - buzz.isna().mean()

post_id            1.000
text               0.975
post_text          0.570
shared_text        0.435
time               1.000
image              0.215
video              0.120
video_thumbnail    0.120
video_id           0.120
likes              1.000
comments           1.000
shares             1.000
post_url           0.325
link               0.075
user_id            1.000
username           1.000
is_live            1.000
factcheck          0.000
shared_post_id     0.310
shared_time        0.310
shared_user_id     0.310
shared_username    0.310
shared_post_url    0.310
images             1.000
dtype: float64